/**
 * /report — Post a structured report to #ops
 *
 * Supports two report types:
 *   - weekly: Weekly summary with metrics (inline fields) + highlights/blockers/next
 *   - checklist: Daily execution checklist with outbound/content/admin sections
 *
 * Posts template embeds with placeholder fields. Currently attributed to
 * Corven (single-agent runtime). When dedicated squad agents are added,
 * attribution can be switched to the ops agent.
 *
 * Type: Routed → #ops
 */

import {
  ChannelType,
  type ChatInputCommandInteraction,
  EmbedBuilder,
  MessageFlags,
  SlashCommandBuilder,
  type TextChannel,
} from 'discord.js';
import { AGENT_COLORS } from '../utils/constants.js';
import { formatTimestamp } from '../utils/helpers.js';
import { logAction } from '../services/audit-logger.js';
import type { Command } from '../types.js';

const DESTINATION_CHANNEL = 'ops';

function getWeekRange(): string {
  const now = new Date();
  const day = now.getDay();
  // Monday of this week
  const monday = new Date(now);
  monday.setDate(now.getDate() - ((day + 6) % 7));
  // Friday of this week
  const friday = new Date(monday);
  friday.setDate(monday.getDate() + 4);

  const fmt = (d: Date) => {
    const months = [
      'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
      'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec',
    ];
    return `${months[d.getMonth()]} ${d.getDate()}`;
  };

  return `${fmt(monday)}\u2013${fmt(friday)}`;
}

function buildWeeklyEmbed(): EmbedBuilder {
  const weekRange = getWeekRange();

  return new EmbedBuilder()
    .setTitle(`\u{1f4cb} Week of ${weekRange}`)
    .setColor(AGENT_COLORS.CORVEN)
    .setDescription('Weekly ops summary.')
    .addFields(
      { name: '\u{1f4ca} DMs Sent', value: '— / —', inline: true },
      { name: '\u{1f4e7} Emails Sent', value: '— / —', inline: true },
      { name: '\u{1f4ac} Responses', value: '—', inline: true },
      { name: '\u{1f525} Sparks Booked', value: '—', inline: true },
      { name: '\u{1f4c8} Response Rate', value: '—%', inline: true },
      { name: '\u{1f4b0} Pipeline Value', value: '\u20ac—', inline: true },
      {
        name: 'Highlights',
        value: '_Fill in highlights — reply in thread_',
        inline: false,
      },
      {
        name: 'Blockers',
        value: '_Fill in blockers — reply in thread_',
        inline: false,
      },
      {
        name: 'Next Week',
        value: '_Fill in plans — reply in thread_',
        inline: false,
      },
    )
    .setFooter({ text: `${formatTimestamp()} \u00b7 via Corven` });
}

function buildChecklistEmbed(): EmbedBuilder {
  const today = new Date().toISOString().split('T')[0];

  return new EmbedBuilder()
    .setTitle(`\u{1f4cb} Checklist \u2014 ${today}`)
    .setColor(AGENT_COLORS.CORVEN)
    .setDescription("Today's execution tasks (30\u201360 min).")
    .addFields(
      {
        name: 'Outbound',
        value:
          '\u2610 Send 10 DMs (segment A)\n\u2610 Send 10 emails (segment A)\n\u2610 Follow-up Day 3 batch',
        inline: false,
      },
      {
        name: 'Content',
        value: '\u2610 Post 1 (scheduled)\n\u2610 Engage 5 comments',
        inline: false,
      },
      {
        name: 'Admin',
        value:
          '\u2610 Log responses in HubSpot\n\u2610 Update Notion board',
        inline: false,
      },
    )
    .setFooter({ text: 'Generated by Corven' });
}

const command: Command = {
  data: new SlashCommandBuilder()
    .setName('report')
    .setDescription('Post a structured report to #ops')
    .addStringOption((opt) =>
      opt
        .setName('type')
        .setDescription('Report type')
        .setRequired(true)
        .addChoices(
          { name: 'Weekly Summary', value: 'weekly' },
          { name: 'Daily Checklist', value: 'checklist' },
        ),
    ),

  async execute(interaction: ChatInputCommandInteraction) {
    await interaction.deferReply({ flags: MessageFlags.Ephemeral });

    const reportType = interaction.options.getString('type', true);
    const guild = interaction.guild!;

    // Find #ops
    const opsChannel = guild.channels.cache.find(
      (ch) => ch.name === DESTINATION_CHANNEL && ch.type === ChannelType.GuildText,
    ) as TextChannel | undefined;

    if (!opsChannel) {
      await interaction.editReply({
        content: `\u274c Channel #${DESTINATION_CHANNEL} not found. Run \`/setup full\` to create it.`,
      });
      return;
    }

    // Build embed based on type
    const embed =
      reportType === 'weekly' ? buildWeeklyEmbed() : buildChecklistEmbed();

    const label =
      reportType === 'weekly' ? 'Weekly report' : 'Daily checklist';

    // Post to #ops
    const message = await opsChannel.send({ embeds: [embed] });

    // Audit log
    await logAction(
      guild,
      'REPORT',
      `\u{1f4cb} ${label} posted in #${DESTINATION_CHANNEL}`,
    );

    await interaction.editReply({
      content: `\u{1f4cb} ${label} posted \u2192 ${message.url}`,
    });
  },
};

export default command;
